// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC-62i2P628TLwDltl9C2LdOyc-VNASCpc",
    appId: "1:580239882832:web:68ec03970b191bd0f6ef55",
    messagingSenderId: "580239882832",
    projectId: "afya-yangu-a6e00",
    authDomain: "afya-yangu-a6e00.firebaseapp.com",
    storageBucket: "afya-yangu-a6e00.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyC-62i2P628TLwDltl9C2LdOyc-VNASCpc",
    appId: "1:580239882832:android:YOUR_ANDROID_APP_ID_SUFFIX",
    messagingSenderId: "580239882832",
    projectId: "afya-yangu-a6e00",
    storageBucket: "afya-yangu-a6e00.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyC-62i2P628TLwDltl9C2LdOyc-VNASCpc",
    appId: "1:580239882832:ios:YOUR_IOS_APP_ID_SUFFIX",
    messagingSenderId: "580239882832",
    projectId: "afya-yangu-a6e00",
    storageBucket: "afya-yangu-a6e00.appspot.com",
    iosBundleId: "com.example.patientTracker",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyC-62i2P628TLwDltl9C2LdOyc-VNASCpc",
    appId: "1:580239882832:ios:YOUR_MACOS_APP_ID_SUFFIX",
    messagingSenderId: "580239882832",
    projectId: "afya-yangu-a6e00",
    storageBucket: "afya-yangu-a6e00.appspot.com",
    iosBundleId: "com.example.patientTracker",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyC-62i2P628TLwDltl9C2LdOyc-VNASCpc",
    appId: "1:580239882832:web:YOUR_WINDOWS_APP_ID_SUFFIX",
    messagingSenderId: "580239882832",
    projectId: "afya-yangu-a6e00",
    authDomain: "afya-yangu-a6e00.firebaseapp.com",
    storageBucket: "afya-yangu-a6e00.appspot.com",
  );
}
